// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc6R3f1PuIhR2iuMQqZ3KeBZ9wngYkwqM',
    appId: '1:280297372745:web:6dfa245a90a8dc23a21398',
    messagingSenderId: '280297372745',
    projectId: 'flutter-ui-9e060',
    authDomain: 'flutter-ui-9e060.firebaseapp.com',
    storageBucket: 'flutter-ui-9e060.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOXougT2rQ5CKb_ERz13OjlmeSNRG8o2M',
    appId: '1:280297372745:android:0a833a48a71dcdd3a21398',
    messagingSenderId: '280297372745',
    projectId: 'flutter-ui-9e060',
    storageBucket: 'flutter-ui-9e060.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3PxiQ_l6o0MRrwPcszYHg4ng98cokSnk',
    appId: '1:280297372745:ios:a6e2c55d607f8367a21398',
    messagingSenderId: '280297372745',
    projectId: 'flutter-ui-9e060',
    storageBucket: 'flutter-ui-9e060.appspot.com',
    iosBundleId: 'com.example.flutterUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3PxiQ_l6o0MRrwPcszYHg4ng98cokSnk',
    appId: '1:280297372745:ios:bfb24a961ae7546da21398',
    messagingSenderId: '280297372745',
    projectId: 'flutter-ui-9e060',
    storageBucket: 'flutter-ui-9e060.appspot.com',
    iosBundleId: 'com.example.flutterUi.RunnerTests',
  );
}
